### ISSUE TITLE
Bme280 data issue

### ISSUE THREAD

**Issue by RySaw** [BYU-Spacecraft-Group/TriSeptRaspberryPi#2]
In the BME280 test.py and sensorsCombined.py files, the readings make perfect sense and seem to be accurate. In the BME280Advanced.py and totalCombined files, the readings from the bme280 sensor make no sense.

**Comment by tylermnielsen** [comment]
Solved, it was a problem with disabling overscanning to get higher BME sensing speeds. Switching to OVERSCAN_X1, the next fastest looks like it solved it, I got 854.008282940384 (BME) and 854.7421242186454 (MPR).
